# ~/.config/alacritty/alacritty.toml
[window]
# Set the dimensions (columns x rows)
dimensions = { columns = 85, lines = 26 }

[font]
# Font family and style
normal = { family = "MesloLGS NF", style = "Regular" }
# Font size
size = 13.0

# Enable anti-aliasing for better  font rendering

offset.x = 1
offset.y = 1
